### ISSUE TITLE
Blank admin page after install

### ISSUE THREAD

**Issue by dantaylorseo** [dannyvankooten/wordpress-recent-facebook-posts#6]
Hi there after install admin page is blank. Page fully loads, no formatting errors. Nothing in error_log or with WP_DEBUG true

**Comment by lid3rs** [comment]
The same, just blank screen with WP admin menus.

**Comment by sarumbear** [comment]
Same here. The settings page for the plugin is blank, hence not possible to use the plugin. WP v4.1

I see that last reply is almost a month ago. I appreciate if the author says outright that he is not interested in debugging this issue so that we know where we stand.

**Comment by dannyvankooten** [comment]
Hi @sarumbear , I'm definitely interested in debugging this issue but also very busy with work. Sorry.

Do you happen to know which PHP version you're running?

**Comment by dannyvankooten** [comment]
Hey all, just tracked down the source of this issue. Pushing out an update to WordPress.org as we speak! Thank you for your patience on this one.

**Comment by sarumbear** [comment]
Thank you.
